const fs = require('node:fs');
const fsPromises = require('node:fs/promises');
const path = require('node:path');
const PDFDocument = require('pdfkit');
const database = require('../../config/database');
const dashboardService = require('../dashboard/dashboardService');
const reportJobService = require('./reportJobService');

const REPORT_TYPE_PHARMACY_SUMMARY = 'pharmacy_summary_pdf';
const reportsDir = path.join(__dirname, '..', '..', '..', 'public', 'reports');

function formatCurrencyIDR(value) {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0
  }).format(Number(value ?? 0));
}

function formatNumber(value) {
  return new Intl.NumberFormat('id-ID').format(Number(value ?? 0));
}

function formatDateTime(value) {
  return new Intl.DateTimeFormat('id-ID', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'Asia/Jakarta'
  }).format(new Date(value));
}

async function ensureReportsDir() {
  await fsPromises.mkdir(reportsDir, { recursive: true });
}

function createPdfDocument(outputPath) {
  const document = new PDFDocument({ size: 'A4', margin: 40 });
  const stream = fs.createWriteStream(outputPath);
  document.pipe(stream);

  return {
    document,
    done: new Promise((resolve, reject) => {
      stream.on('finish', resolve);
      stream.on('error', reject);
      document.on('error', reject);
    })
  };
}

function drawHeader(document, title, generatedBy) {
  document.save();
  document.roundedRect(40, 36, 56, 56, 10).fill('#10b981');
  document.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18).text('PR', 40, 56, {
    width: 56,
    align: 'center'
  });
  document.restore();

  document.fillColor('#1e293b').font('Helvetica-Bold').fontSize(22).text('Prosperoudia', 110, 44);
  document.fillColor('#475569').font('Helvetica').fontSize(11).text(title, 110, 72);
  document.text(`Generated: ${formatDateTime(new Date())}`, 110, 88);
  document.text(`Generated by: ${generatedBy}`, 110, 104);
}

function drawMetricCard(document, x, y, width, title, value, accentColor) {
  document.save();
  document.roundedRect(x, y, width, 72, 12).fill('#f8fafc');
  document.roundedRect(x, y, 8, 72, 12).fill(accentColor);
  document.fillColor('#64748b').font('Helvetica').fontSize(10).text(title, x + 20, y + 16, { width: width - 24 });
  document.fillColor('#0f172a').font('Helvetica-Bold').fontSize(18).text(value, x + 20, y + 36, { width: width - 24 });
  document.restore();
}

function drawTable(document, x, y, width, columns, rows, headerColor = '#0f766e') {
  const headerHeight = 26;
  const rowHeight = 24;
  const totalFlex = columns.reduce((sum, column) => sum + column.width, 0);
  const resolvedColumns = columns.map((column) => ({
    ...column,
    pixelWidth: (column.width / totalFlex) * width
  }));

  let cursorY = y;
  document.save();
  document.roundedRect(x, cursorY, width, headerHeight, 8).fill(headerColor);

  let cursorX = x;
  resolvedColumns.forEach((column) => {
    document.fillColor('#ffffff').font('Helvetica-Bold').fontSize(10).text(column.label, cursorX + 8, cursorY + 8, {
      width: column.pixelWidth - 16,
      align: column.align ?? 'left'
    });
    cursorX += column.pixelWidth;
  });

  cursorY += headerHeight;
  rows.forEach((row, index) => {
    document.fillColor(index % 2 === 0 ? '#f8fafc' : '#e2e8f0').rect(x, cursorY, width, rowHeight).fill();
    let cellX = x;
    resolvedColumns.forEach((column) => {
      document.fillColor('#0f172a').font('Helvetica').fontSize(9).text(String(row[column.key] ?? '-'), cellX + 8, cursorY + 7, {
        width: column.pixelWidth - 16,
        align: column.align ?? 'left'
      });
      cellX += column.pixelWidth;
    });
    cursorY += rowHeight;
  });

  document.restore();
  return cursorY;
}

async function getTopSellingMedicines(limit = 5, trx = database) {
  return trx('order_items as oi')
    .innerJoin('orders as o', 'o.id', 'oi.order_id')
    .groupBy('oi.medicine_id', 'oi.medicine_sku_snapshot', 'oi.medicine_name_snapshot')
    .select(
      'oi.medicine_id',
      'oi.medicine_sku_snapshot as sku',
      'oi.medicine_name_snapshot as name'
    )
    .sum({ total_quantity: 'oi.quantity' })
    .sum({ total_sales: 'oi.total_price' })
    .whereIn('o.status', ['confirmed', 'completed'])
    .orderBy('total_quantity', 'desc')
    .limit(limit);
}

async function getExpiringBatches(limit = 5, trx = database) {
  return trx('inventory_batches as ib')
    .innerJoin('medicines as m', 'm.id', 'ib.medicine_id')
    .select(
      'ib.batch_number',
      'ib.expired_at',
      'ib.quantity_remaining',
      'm.sku',
      'm.name as medicine_name'
    )
    .where('ib.quantity_remaining', '>', 0)
    .whereRaw("ib.expired_at <= NOW() + INTERVAL '90 days'")
    .orderBy('ib.expired_at', 'asc')
    .limit(limit);
}

async function generatePharmacySummaryPdf({ createdBy, sessionUser }) {
  await ensureReportsDir();

  const job = await reportJobService.queueReportJob({
    report_type: REPORT_TYPE_PHARMACY_SUMMARY,
    filters: { scope: 'pharmacy_summary' },
    status: 'processing',
    created_by: createdBy,
    started_at: new Date()
  });

  try {
    const [summary, trend, lowStock, recentOrders, topSelling, expiringBatches] = await Promise.all([
      dashboardService.getDashboardSummary(),
      dashboardService.getOrderTrend(7),
      dashboardService.getLowStockProducts(5),
      dashboardService.getRecentOrders(6),
      getTopSellingMedicines(5),
      getExpiringBatches(5)
    ]);

    const fileName = `report-pharmacy-summary-${Date.now()}.pdf`;
    const absoluteOutputPath = path.join(reportsDir, fileName);
    const publicOutputPath = `/reports/${fileName}`;
    const { document, done } = createPdfDocument(absoluteOutputPath);

    drawHeader(document, 'Pharmacy Summary Report', sessionUser?.full_name || sessionUser?.username || 'System');

    drawMetricCard(document, 40, 140, 122, 'Total Obat', formatNumber(summary.totalMedicines), '#10b981');
    drawMetricCard(document, 174, 140, 122, 'Low Stock', formatNumber(summary.lowStockItems), '#f59e0b');
    drawMetricCard(document, 308, 140, 122, 'Order 7 Hari', formatNumber(summary.recentOrders), '#0f766e');
    drawMetricCard(document, 442, 140, 122, 'Pendapatan', formatCurrencyIDR(summary.totalRevenue), '#1e293b');

    document.fillColor('#0f172a').font('Helvetica-Bold').fontSize(14).text('Tren Order 7 Hari', 40, 244);
    drawTable(
      document,
      40,
      266,
      525,
      [
        { key: 'day', label: 'Hari', width: 1.4 },
        { key: 'orders', label: 'Order', width: 1.1, align: 'right' },
        { key: 'revenue', label: 'Pendapatan', width: 2, align: 'right' }
      ],
      trend.labels.map((label, index) => ({
        day: label,
        orders: formatNumber(trend.orders[index] ?? 0),
        revenue: formatCurrencyIDR(trend.revenue[index] ?? 0)
      }))
    );

    let nextY = 266 + 26 + trend.labels.length * 24 + 20;

    document.fillColor('#0f172a').font('Helvetica-Bold').fontSize(14).text('Obat Low Stock', 40, nextY);
    nextY = drawTable(
      document,
      40,
      nextY + 22,
      525,
      [
        { key: 'sku', label: 'SKU', width: 1.2 },
        { key: 'name', label: 'Obat', width: 2.6 },
        { key: 'stock', label: 'Stok / Min', width: 1.6, align: 'right' }
      ],
      lowStock.map((item) => ({
        sku: item.sku,
        name: item.name,
        stock: `${formatNumber(item.current_stock)} / ${formatNumber(item.threshold)}`
      })),
      '#b45309'
    );

    if (nextY > 690) {
      document.addPage();
      nextY = 40;
    } else {
      nextY += 20;
    }

    document.fillColor('#0f172a').font('Helvetica-Bold').fontSize(14).text('Obat Terlaris', 40, nextY);
    nextY = drawTable(
      document,
      40,
      nextY + 22,
      525,
      [
        { key: 'sku', label: 'SKU', width: 1.1 },
        { key: 'name', label: 'Obat', width: 2.4 },
        { key: 'qty', label: 'Qty', width: 1, align: 'right' },
        { key: 'sales', label: 'Penjualan', width: 1.8, align: 'right' }
      ],
      topSelling.map((item) => ({
        sku: item.sku,
        name: item.name,
        qty: formatNumber(item.total_quantity),
        sales: formatCurrencyIDR(item.total_sales)
      })),
      '#0f766e'
    );

    nextY += 20;
    document.fillColor('#0f172a').font('Helvetica-Bold').fontSize(14).text('Batch Mendekati Expiry', 40, nextY);
    nextY = drawTable(
      document,
      40,
      nextY + 22,
      525,
      [
        { key: 'batch', label: 'Batch', width: 1.4 },
        { key: 'medicine', label: 'Obat', width: 2.4 },
        { key: 'expiry', label: 'Expired', width: 1.2 },
        { key: 'stock', label: 'Sisa', width: 0.9, align: 'right' }
      ],
      expiringBatches.map((item) => ({
        batch: item.batch_number,
        medicine: `${item.sku} - ${item.medicine_name}`,
        expiry: new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(item.expired_at)),
        stock: formatNumber(item.quantity_remaining)
      })),
      '#7c3aed'
    );

    if (nextY > 690) {
      document.addPage();
      nextY = 40;
    } else {
      nextY += 20;
    }

    document.fillColor('#0f172a').font('Helvetica-Bold').fontSize(14).text('Order Terbaru', 40, nextY);
    drawTable(
      document,
      40,
      nextY + 22,
      525,
      [
        { key: 'order', label: 'Order', width: 1.5 },
        { key: 'customer', label: 'Pelanggan', width: 2.2 },
        { key: 'status', label: 'Status', width: 1.2 },
        { key: 'total', label: 'Total', width: 1.5, align: 'right' }
      ],
      recentOrders.map((item) => ({
        order: item.order_number,
        customer: item.customer_name,
        status: item.status,
        total: formatCurrencyIDR(item.total_amount)
      })),
      '#1e293b'
    );

    document.end();
    await done;

    return reportJobService.markReportJobCompleted(job.id, {
      output_file_path: publicOutputPath,
      error_summary: null
    });
  } catch (error) {
    await reportJobService.markReportJobFailed(job.id, {
      error_summary: [{ message: error.message || 'PDF report generation failed' }]
    });
    throw error;
  }
}

module.exports = {
  REPORT_TYPE_PHARMACY_SUMMARY,
  generatePharmacySummaryPdf
};
