const HALODOC_SNAPSHOT_DATE = '2026-06-06';

const categories = [
  {
    id: 1,
    code: 'OBAT-RESEP',
    name: 'Obat Resep',
    description: 'Kategori obat yang memerlukan resep atau edukasi penggunaan dokter/apoteker.'
  },
  {
    id: 2,
    code: 'OBAT-BEBAS',
    name: 'Obat Bebas',
    description: 'Kategori obat bebas dan obat bebas terbatas untuk keluhan umum.'
  },
  {
    id: 3,
    code: 'VIT-SUPL',
    name: 'Vitamin & Suplemen',
    description: 'Vitamin, mineral, dan suplemen kesehatan harian.'
  },
  {
    id: 4,
    code: 'ALKES',
    name: 'Alat Kesehatan',
    description: 'Alat kesehatan rumah tangga dan perlengkapan penunjang medis.'
  }
];

const suppliers = [
  {
    id: 1,
    code: 'SUP-HALO-RSP',
    name: 'Halodoc Snapshot Obat Rutin',
    phone: '0210001001',
    email: 'feed-obatrutin@prosperoudia.local',
    address: 'Sumber kategori Halodoc: Obat Rutin'
  },
  {
    id: 2,
    code: 'SUP-HALO-BBS',
    name: 'Halodoc Snapshot Obat Bebas',
    phone: '0210001002',
    email: 'feed-obatbebas@prosperoudia.local',
    address: 'Sumber kategori Halodoc: Batuk, Pilek & Flu'
  },
  {
    id: 3,
    code: 'SUP-HALO-VIT',
    name: 'Halodoc Snapshot Vitamin',
    phone: '0210001003',
    email: 'feed-vitamin@prosperoudia.local',
    address: 'Sumber kategori Halodoc: Vitamin & Suplemen'
  },
  {
    id: 4,
    code: 'SUP-HALO-ALK',
    name: 'Halodoc Snapshot Alat Kesehatan',
    phone: '0210001004',
    email: 'feed-alkes@prosperoudia.local',
    address: 'Sumber kategori Halodoc: Alat Kesehatan'
  }
];

const medicines = [
  {
    id: 1,
    sku: 'RSP-CAND-8-3S',
    name: 'Candesartan Dexa 8 mg 3 Strip (10 Tablet/Strip)',
    brand_name: 'Dexa',
    category_id: 1,
    supplier_id: 1,
    description: 'Obat rutin untuk hipertensi dan gagal jantung. Penggunaan harus berdasarkan resep atau hasil konsultasi dokter.',
    composition: 'Candesartan cilexetil 8 mg',
    dosage: 'Sesuai resep dokter.',
    dosage_form: 'Tablet',
    strength: '8 mg',
    side_effects: 'Pusing, kelelahan, tekanan darah rendah, peningkatan kalium.',
    unit_price: 18500,
    minimum_stock_threshold: 12,
    requires_prescription: true
  },
  {
    id: 2,
    sku: 'RSP-AMLO-10-3S',
    name: 'Amlodipine 10 mg 3 Strip (10 Tablet/Strip)',
    brand_name: 'Amlodipine',
    category_id: 1,
    supplier_id: 1,
    description: 'Obat rutin golongan antihipertensi untuk membantu mengontrol tekanan darah tinggi.',
    composition: 'Amlodipine 10 mg',
    dosage: 'Sesuai resep dokter.',
    dosage_form: 'Tablet',
    strength: '10 mg',
    side_effects: 'Pusing, bengkak pada tungkai, wajah terasa hangat, lelah.',
    unit_price: 15400,
    minimum_stock_threshold: 12,
    requires_prescription: true
  },
  {
    id: 3,
    sku: 'RSP-METF-500-10S',
    name: 'Metformin 500 mg 10 Strip (10 Tablet/Strip)',
    brand_name: 'Metformin',
    category_id: 1,
    supplier_id: 1,
    description: 'Obat rutin untuk membantu mengontrol kadar gula darah pada diabetes tipe 2.',
    composition: 'Metformin 500 mg',
    dosage: 'Sesuai resep dokter.',
    dosage_form: 'Tablet',
    strength: '500 mg',
    side_effects: 'Mual, diare, rasa logam di mulut, kembung.',
    unit_price: 17600,
    minimum_stock_threshold: 10,
    requires_prescription: true
  },
  {
    id: 4,
    sku: 'RSP-ATOR-20-3S',
    name: 'Atorvastatin 20 mg 3 Strip (10 Tablet/Strip)',
    brand_name: 'Atorvastatin',
    category_id: 1,
    supplier_id: 1,
    description: 'Obat rutin golongan statin untuk membantu menurunkan kolesterol darah.',
    composition: 'Atorvastatin 20 mg',
    dosage: 'Sesuai resep dokter.',
    dosage_form: 'Tablet',
    strength: '20 mg',
    side_effects: 'Nyeri otot, gangguan pencernaan, pusing ringan.',
    unit_price: 37200,
    minimum_stock_threshold: 10,
    requires_prescription: true
  },
  {
    id: 5,
    sku: 'BBS-VICKS-44-54',
    name: 'Vicks Formula 44 Sirup 54 ml',
    brand_name: 'Vicks',
    category_id: 2,
    supplier_id: 2,
    description: 'Sirup obat batuk untuk membantu meredakan batuk kering, terutama yang mengganggu istirahat malam.',
    composition: 'Per 5 ml: Dextromethorphan HBr 5 mg, Doxylamine Succinate 2 mg',
    dosage: 'Dewasa dan anak >12 tahun: 10 ml setiap 4-6 jam. Anak 6-12 tahun: 5 ml setiap 4-6 jam.',
    dosage_form: 'Sirup',
    strength: '54 ml',
    side_effects: 'Mengantuk, pusing, mual, konstipasi, penglihatan kabur.',
    unit_price: 25200,
    minimum_stock_threshold: 15,
    requires_prescription: false
  },
  {
    id: 6,
    sku: 'BBS-BETA-MWG-190',
    name: 'Betadine Mouthwash and Gargle 190 ml',
    brand_name: 'Betadine',
    category_id: 2,
    supplier_id: 2,
    description: 'Obat kumur antiseptik untuk membantu perawatan mulut dan tenggorokan.',
    composition: 'Povidone-iodine',
    dosage: 'Gunakan sesuai petunjuk pada kemasan.',
    dosage_form: 'Larutan kumur',
    strength: '190 ml',
    side_effects: 'Iritasi lokal ringan pada pengguna sensitif.',
    unit_price: 45400,
    minimum_stock_threshold: 8,
    requires_prescription: false
  },
  {
    id: 7,
    sku: 'BBS-DEGI-025-10',
    name: 'Degirol Hisap 0.25 mg 10 Tablet',
    brand_name: 'Degirol',
    category_id: 2,
    supplier_id: 2,
    description: 'Tablet hisap untuk membantu meredakan keluhan tenggorokan.',
    composition: 'Dequalinium chloride 0.25 mg',
    dosage: 'Gunakan sesuai petunjuk pada kemasan atau anjuran tenaga kesehatan.',
    dosage_form: 'Tablet hisap',
    strength: '0.25 mg',
    side_effects: 'Mulut terasa tidak nyaman atau iritasi ringan.',
    unit_price: 16300,
    minimum_stock_threshold: 10,
    requires_prescription: false
  },
  {
    id: 8,
    sku: 'BBS-PARA-10',
    name: 'Paratusin 10 Tablet',
    brand_name: 'Paratusin',
    category_id: 2,
    supplier_id: 2,
    description: 'Obat untuk membantu meredakan gejala flu, pilek, demam, dan batuk.',
    composition: null,
    dosage: 'Gunakan sesuai petunjuk pada kemasan.',
    dosage_form: 'Tablet',
    strength: '10 tablet per strip',
    side_effects: 'Mengantuk, mual, atau keluhan lambung ringan.',
    unit_price: 19800,
    minimum_stock_threshold: 12,
    requires_prescription: false
  },
  {
    id: 9,
    sku: 'VIT-NEUR-10',
    name: 'Neurobion Forte 10 Tablet',
    brand_name: 'Neurobion',
    category_id: 3,
    supplier_id: 3,
    description: 'Vitamin neurotropik untuk membantu memenuhi kebutuhan vitamin B1, B6, dan B12 serta mendukung fungsi sistem saraf.',
    composition: 'Vitamin B1, Vitamin B6, Vitamin B12',
    dosage: 'Dosis umum dewasa: 1 tablet sehari.',
    dosage_form: 'Tablet',
    strength: '10 tablet per strip',
    side_effects: 'Mual ringan atau keluhan lambung pada sebagian pengguna.',
    unit_price: 55000,
    minimum_stock_threshold: 10,
    requires_prescription: false
  },
  {
    id: 10,
    sku: 'VIT-SANG-10',
    name: 'Sangobion 10 Kapsul',
    brand_name: 'Sangobion',
    category_id: 3,
    supplier_id: 3,
    description: 'Suplemen penambah darah dengan zat besi dan vitamin pendukung pembentukan sel darah merah.',
    composition: 'Zat besi dan vitamin pendukung pembentukan darah',
    dosage: 'Gunakan sesuai petunjuk pada kemasan atau anjuran tenaga kesehatan.',
    dosage_form: 'Kapsul',
    strength: '10 kapsul per strip',
    side_effects: 'Mual, konstipasi, atau feses berwarna lebih gelap.',
    unit_price: 24900,
    minimum_stock_threshold: 10,
    requires_prescription: false
  },
  {
    id: 11,
    sku: 'VIT-VTMC-500-2',
    name: 'Vitacimin 500 mg Rasa Lemon 2 Tablet',
    brand_name: 'Vitacimin',
    category_id: 3,
    supplier_id: 3,
    description: 'Suplemen vitamin C kunyah untuk membantu memenuhi kebutuhan vitamin C harian.',
    composition: 'Vitamin C 500 mg',
    dosage: 'Gunakan sesuai petunjuk pada kemasan.',
    dosage_form: 'Tablet kunyah',
    strength: '500 mg',
    side_effects: 'Perut terasa tidak nyaman bila dikonsumsi berlebihan.',
    unit_price: 3000,
    minimum_stock_threshold: 20,
    requires_prescription: false
  },
  {
    id: 12,
    sku: 'VIT-IMBF-10',
    name: 'Imboost Force 10 Kaplet',
    brand_name: 'Imboost',
    category_id: 3,
    supplier_id: 3,
    description: 'Suplemen untuk membantu menjaga daya tahan tubuh.',
    composition: null,
    dosage: 'Gunakan sesuai petunjuk pada kemasan.',
    dosage_form: 'Kaplet',
    strength: '10 kaplet per strip',
    side_effects: 'Keluhan lambung ringan pada sebagian pengguna.',
    unit_price: 90500,
    minimum_stock_threshold: 8,
    requires_prescription: false
  },
  {
    id: 13,
    sku: 'ALK-OMRN-MC246',
    name: 'Omron Digital Thermometer MC-246',
    brand_name: 'Omron',
    category_id: 4,
    supplier_id: 4,
    description: 'Termometer digital untuk pemantauan suhu tubuh di rumah.',
    composition: null,
    dosage: 'Gunakan sesuai panduan penggunaan alat.',
    dosage_form: 'Unit',
    strength: 'Per piece',
    side_effects: null,
    unit_price: 81900,
    minimum_stock_threshold: 6,
    requires_prescription: false
  },
  {
    id: 14,
    sku: 'ALK-ONEMED-TEST',
    name: 'Onemed Test Kehamilan Strip',
    brand_name: 'Onemed',
    category_id: 4,
    supplier_id: 4,
    description: 'Alat tes kehamilan strip untuk penggunaan mandiri.',
    composition: null,
    dosage: 'Gunakan sesuai panduan pada kemasan alat.',
    dosage_form: 'Strip',
    strength: 'Per piece',
    side_effects: null,
    unit_price: 5200,
    minimum_stock_threshold: 12,
    requires_prescription: false
  },
  {
    id: 15,
    sku: 'ALK-SPUIT-3CC',
    name: 'Spuit 3 cc',
    brand_name: 'Spuit',
    category_id: 4,
    supplier_id: 4,
    description: 'Alat suntik sekali pakai ukuran 3 cc. Pembelian memerlukan resep/edukasi penggunaan.',
    composition: null,
    dosage: 'Gunakan sesuai tindakan medis dan edukasi tenaga kesehatan.',
    dosage_form: 'Piece',
    strength: '3 cc',
    side_effects: null,
    unit_price: 5400,
    minimum_stock_threshold: 20,
    requires_prescription: true
  },
  {
    id: 16,
    sku: 'ALK-HOTCOLD-PACK',
    name: 'Hot / Cold Pack Kompres',
    brand_name: 'Hot / Cold Pack',
    category_id: 4,
    supplier_id: 4,
    description: 'Kompres panas/dingin untuk membantu penanganan nyeri dan bengkak ringan.',
    composition: null,
    dosage: 'Gunakan sesuai panduan penggunaan alat.',
    dosage_form: 'Piece',
    strength: 'Per piece',
    side_effects: null,
    unit_price: 46900,
    minimum_stock_threshold: 6,
    requires_prescription: false
  }
].map((item) => ({
  ...item,
  is_active: true
}));

module.exports = {
  HALODOC_SNAPSHOT_DATE,
  categories,
  suppliers,
  medicines,
  sourcePages: {
    prescription: 'https://www.halodoc.com/obat-dan-vitamin/kategori/obat-rutin',
    otc: 'https://www.halodoc.com/obat-dan-vitamin/kategori/batuk-pilek-dan-flu',
    supplements: 'https://www.halodoc.com/obat-dan-vitamin/kategori/vitamin-dan-suplemen',
    medicalDevices: 'https://www.halodoc.com/obat-dan-vitamin/kategori/alat-kesehatan'
  }
};
